# Generated by Django 4.1 on 2024-05-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_id', models.IntegerField()),
                ('expense_name', models.CharField(max_length=255)),
                ('expense_desc', models.TextField()),
                ('expense_amount', models.ImageField(upload_to='')),
                ('expense_date', models.DateField()),
            ],
        ),
    ]
