# Generated by Django 4.1 on 2024-05-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='expense_amount',
            field=models.IntegerField(),
        ),
    ]
