# Generated by Django 4.1 on 2024-05-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0003_rename_expense_name_tracker_expense_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='expense_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
