# Generated by Django 4.1 on 2024-05-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0004_alter_tracker_expense_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='expense_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='expense_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
